baseURL = 'http://kafka.apache.org/34/documentation'
languageCode = 'en-us'
title = 'Apache Kafka documentation'
pygmentsUseClasses = true

[params]
akVersion = '34'
akDotVersion = '3.4'
akFullDotVersion = '3.4.0'
scalaVersion = '2.13'

[markup]
[markup.goldmark]
[markup.goldmark.renderer]
unsafe = true