baseURL = 'http://kafka.apache.org/34/documentation'
languageCode = 'en-us'
title = 'Apache Kafka documentation'
theme = 'ak-docs-v1'
pygmentsUseClasses = true

[params]
akVersion = '35'
akDotVersion = '3.5'
akFullDotVersion = '3.5.0'
scalaVersion = '2.13'

[markup]
[markup.goldmark]
[markup.goldmark.renderer]
unsafe = true