# theme.toml template for a Hugo theme
# See https://github.com/gohugoio/hugoThemes#themetoml for an example
# Based on "https://github.com/alex-shpak/hugo-book" used by Flink project
name = "ak-docs"
license = "MIT"
licenselink = "https://github.com/apache/kafka/blob/master/LICENSE"
description = "Apache Kafka documentation theme"
homepage = "https://github.com/apache/kafka"
tags = ["documentation"]
features = []
min_version = "0.68"

[author]
  name = "kafka community"
  homepage = "https://github.com/apache/kafka"
